### ISSUE TITLE
User Needs Revision Parent Issue

### ISSUE THREAD

**Issue by mertaksac** [FRAME-NEXT/FRAME#25]
User Needs are going through a revision to better suit the developments in FRAME NEXT.

Peter has put together a document describing the possible changes that will need to be considered and pointed out that a number of high-level decisions would be needed to be taken in the project before he dives deep to make these revisions.

You can find the mentioned document here:  https://files.austriatech.at/f/272bab0cd2c042fb8062/

I am transferring that discussion here to be able to utilize the comment facility of GitHub, which will make it easier to raise and follow up ideas.

_This GitHub issue will serve as a parent for all other issues related to the revision of the User Needs._ Below are the 5 main topics that Peter has raised in his initial document. _Each of the points below will (potentially) turn into separate GitHub issues, to be discussed in detail._

**Points and questions raised by Peter:**

- [ ] **1) Systems vs Services**

Questions – 
- do we change ALL the “The system shall … “ to “The service shall …”, or keep some of “The system shall … “?

- [ ] **2)C-ITS**

Questions –
- Are all of the additional 230 User Needs still correct?
- does the terminology need to be brought up-to date?
- a number of these User Needs state explicitly that they relate to “Floating Car Data (FCD)” or to “Extended Floating Car Data (XFCD)” – can/should they remain as they are?
- are there any new User Needs that should be created and included in the FRAME Architecture?

- [ ] **3) Freight &amp; Fleet Management**

- [ ] **4) Group 1 User Needs**

Questions –
- Should they keep their wording, or should that be changed to ‘Services that are supported by the FRAME Architecture shall…’ (see also Point 1).
- Do we add Group 1 User Needs to the EA Tool? If so, how? If not, what do we dowith them?
- If Group 1 User Needs are added to the EA Tool, should they be linked to parts of the Motivational or Business Layers? If so, would they provide a sort of ‘check list’ for users?

- [ ] **5) Cross References**

Questions –
- do we wish to maintain the cross-references in the new EA Tool?

**Comment by mertaksac** [comment]
The [User Needs Revision](https://files.austriatech.at/f/272bab0cd2c042fb8062/) document still contains questions rather than answers.

Please kindly comment if this issue can be marked as closed. (due to inactivity)

**Comment by burespe1** [comment]
I put the document in question here [FRAME User Needs - Revision - 03.docx](https://github.com/user-attachments/files/25934588/FRAME.User.Needs.-.Revision.-.03.docx). 

I think all of the issues **are still valid** and ready for a sub-issue. 

proposal @mertaksac: please create subissues addressing the individual problems

**Comment by bossomr** [comment]
I have had a quick look at the document and the questions that have been included.  In my view, unless we already have one, we should set up a task to review and answer all the questions, the result of which should be proposals for the necessary revisions to the user needs that could then be approved by the FRAME Maintainers.  Once approved and implemented, I think the result would be a new version of the FRAME repository.
